# For more information on GitHub Actions for Python projects, see: https://git.io/JtENw

name: Test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 2-6'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # pip cache dependencies to save time
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # When activating macOS, verify pip cache dir at
    #     https://github.com/actions/cache/blob/main/examples.md
    # - uses: actions/cache@v2
    #   if: startsWith(runner.os, 'macOS')
    #   with:
    #     path: ~/Library/Caches/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    # When activating Windows, verify pip cache dir at
    #     https://github.com/actions/cache/blob/main/examples.md
    # - uses: actions/cache@v2
    #   if: startsWith(runner.os, 'Windows')
    #   with:
    #     path: ~\AppData\Local\pip\Cache
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install OS prerequisites
      run: sudo apt-get install ripgrep

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -u -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run with flake8 only checking for Python syntax errors or undefined names
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -u -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run tools using pytest
      run: |
        python -u -m pytest --black --flake8 --mypy --pylint
    - name: Run package
      run: |
        python -u -m innanzi
